netbox_load_balancing/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls

# +
# Import views so the register_model_view is run. This is required for the
# URLs to be set up properly with get_model_urls().
# -
from .views import *  # noqa: F401

app_name = "netbox_load_balancing"

urlpatterns = [
    # Services
    path(
        "service/",
        include(get_model_urls("netbox_load_balancing", "lbservice", detail=False)),
    ),
    path(
        "service/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "lbservice")),
    ),
    # LBService Assignments
    path(
        "service-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "lbserviceassignment", detail=False)
        ),
    ),
    path(
        "service-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "lbserviceassignment")),
    ),
    # Virtual Pools
    path(
        "virtual-pool/",
        include(get_model_urls("netbox_load_balancing", "virtualippool", detail=False)),
    ),
    path(
        "virtual-pool/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualippool")),
    ),
    # Virtual Pool Assignments
    path(
        "virtual-pool-assignments/",
        include(
            get_model_urls(
                "netbox_load_balancing", "virtualippoolassignment", detail=False
            )
        ),
    ),
    path(
        "virtual-pool-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualippoolassignment")),
    ),
    # Virtual Addresses
    path(
        "virtual-address/",
        include(get_model_urls("netbox_load_balancing", "virtualip", detail=False)),
    ),
    path(
        "virtual-address/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualip")),
    ),
    # Listeners
    path(
        "listener/",
        include(get_model_urls("netbox_load_balancing", "listener", detail=False)),
    ),
    path(
        "istener/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "listener")),
    ),
    # Pools
    path(
        "pool/",
        include(get_model_urls("netbox_load_balancing", "pool", detail=False)),
    ),
    path(
        "pool/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "pool")),
    ),
    # Pool Assignments
    path(
        "pool-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "poolassignment", detail=False)
        ),
    ),
    path(
        "pool-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "poolassignment")),
    ),
    # Health Monitors
    path(
        "health-monitor/",
        include(get_model_urls("netbox_load_balancing", "healthmonitor", detail=False)),
    ),
    path(
        "health-monitor/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "healthmonitor")),
    ),
    # Health Monitor Assignments
    path(
        "health-monitor-assignments/",
        include(
            get_model_urls(
                "netbox_load_balancing", "healthmonitorassignment", detail=False
            )
        ),
    ),
    path(
        "health-monitor-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "healthmonitorassignment")),
    ),
    # Members
    path(
        "member/",
        include(get_model_urls("netbox_load_balancing", "member", detail=False)),
    ),
    path(
        "member/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "member")),
    ),
    # Health Monitor Assignments
    path(
        "member-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "memberassignment", detail=False)
        ),
    ),
    path(
        "member-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "memberassignment")),
    ),
]

netbox_load_balancing/models/member.py
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from netbox.models import PrimaryModel, NetBoxModel
from netbox.models.features import ContactsMixin
from netbox.search import SearchIndex, register_search

from netbox_load_balancing.models import Pool, HealthMonitor
from netbox_load_balancing.constants import MEMBER_ASSIGNMENT_MODELS


_all__ = ("Member", "MemberAssignment", "MemberIndex")


class Member(ContactsMixin, PrimaryModel):
    name = models.CharField(
        max_length=255,
    )
    reference = models.CharField(
        max_length=255,
    )
    ip_address = models.ForeignKey(
        to="ipam.IPAddress",
        on_delete=models.CASCADE,
        related_name="%(class)s_members",
    )
    disabled = models.BooleanField(
        default=False,
    )
    prerequisite_models = ("ipam.IPAddress",)

    class Meta:
        verbose_name = _("Member")
        verbose_name_plural = _("Member")
        ordering = ("name", "ip_address")
        unique_together = ("ip_address", "name")

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_load_balancing:member", args=[self.pk])


class MemberAssignment(NetBoxModel):
    assigned_object_type = models.ForeignKey(
        to="contenttypes.ContentType",
        limit_choices_to=MEMBER_ASSIGNMENT_MODELS,
        on_delete=models.CASCADE,
    )
    assigned_object_id = models.PositiveBigIntegerField()
    assigned_object = GenericForeignKey(
        ct_field="assigned_object_type", fk_field="assigned_object_id"
    )
    member = models.ForeignKey(
        to="netbox_load_balancing.Member", on_delete=models.CASCADE
    )
    disabled = models.BooleanField(
        default=False,
    )
    weight = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(32767),
        ],
        default=1,
    )
    clone_fields = ("assigned_object_type", "assigned_object_id")

    prerequisite_models = (
        "netbox_load_balancing.Pool",
        "netbox_load_balancing.Member",
        "netbox_load_balancing.HealthMonitor",
    )

    class Meta:
        indexes = (models.Index(fields=("assigned_object_type", "assigned_object_id")),)
        constraints = (
            models.UniqueConstraint(
                fields=("assigned_object_type", "assigned_object_id", "member"),
                name="%(app_label)s_%(class)s_unique_member",
            ),
        )
        verbose_name = _("LB Member Assignment")
        verbose_name_plural = _("LB Member Assignments")

    def __str__(self):
        return f"{self.assigned_object}: {self.member}"

    def get_absolute_url(self):
        if self.assigned_object:
            return self.assigned_object.get_absolute_url()
        return None


@register_search
class MemberIndex(SearchIndex):
    model = Member
    fields = (
        ("name", 100),
        ("reference", 200),
        ("ip_address", 300),
        ("description", 500),
    )


GenericRelation(
    to=MemberAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="pool",
).contribute_to_class(Pool, "members")

GenericRelation(
    to=MemberAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="health_monitor",
).contribute_to_class(HealthMonitor, "members")

netbox_load_balancing/models/pool.py
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from netbox.models import PrimaryModel, NetBoxModel
from netbox.models.features import ContactsMixin
from netbox.search import SearchIndex, register_search

from netbox_load_balancing.models import LBService
from netbox_load_balancing.constants import POOL_ASSIGNMENT_MODELS
from netbox_load_balancing.choices import (
    PoolAlgorythmChoices,
    PoolSessionPersistenceChoices,
    PoolBackupSessionPersistenceChoices,
)

_all__ = ("Pool", "PoolAssignment", "PoolIndex")


class Pool(ContactsMixin, PrimaryModel):
    name = models.CharField(
        max_length=255,
    )
    listeners = models.ManyToManyField(
        to="netbox_load_balancing.Listener",
        related_name="%(class)s_listeners",
        blank=True,
    )
    algorythm = models.CharField(
        max_length=255,
        choices=PoolAlgorythmChoices,
        default=PoolAlgorythmChoices.LEAST_CONNECTION,
        help_text=_("Load Balancer algorythm for the pool"),
    )
    session_persistence = models.CharField(
        max_length=255,
        choices=PoolSessionPersistenceChoices,
        default=PoolSessionPersistenceChoices.SOURCE_IP,
        help_text=_("Load Balancer session persistence for the pool"),
    )
    backup_persistence = models.CharField(
        max_length=255,
        choices=PoolBackupSessionPersistenceChoices,
        default=PoolBackupSessionPersistenceChoices.NONE,
        help_text=_("Load Balancer backup session persistence for the pool"),
    )
    persistence_timeout = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(1440),
        ],
        default=0,
        help_text=_("Time period for which a persistence session is in effect"),
    )
    backup_timeout = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(1440),
        ],
        default=0,
        help_text=_("Time period for which a backup persistence is in effect"),
    )
    member_port = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(65535),
        ],
        blank=True,
        null=True,
        help_text=_("Backend server port if different from the listener port"),
    )
    disabled = models.BooleanField(
        default=False,
    )
    prerequisite_models = ("netbox_load_balancing.Listener",)

    class Meta:
        verbose_name = _("Pool")
        verbose_name_plural = _("Pools")
        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_load_balancing:pool", args=[self.pk])

    def get_algorythm_color(self):
        return PoolAlgorythmChoices.colors.get(self.algorythm)

    def get_session_persistence_color(self):
        return PoolSessionPersistenceChoices.colors.get(self.session_persistence)

    def get_backup_persistence_color(self):
        return PoolBackupSessionPersistenceChoices.colors.get(self.backup_persistence)


class PoolAssignment(NetBoxModel):
    assigned_object_type = models.ForeignKey(
        to="contenttypes.ContentType",
        limit_choices_to=POOL_ASSIGNMENT_MODELS,
        on_delete=models.CASCADE,
    )
    assigned_object_id = models.PositiveBigIntegerField()
    assigned_object = GenericForeignKey(
        ct_field="assigned_object_type", fk_field="assigned_object_id"
    )
    pool = models.ForeignKey(to="netbox_load_balancing.Pool", on_delete=models.CASCADE)

    clone_fields = ("assigned_object_type", "assigned_object_id")

    prerequisite_models = (
        "ipam.IPRange",
        "netbox_load_balancing.Pool",
    )

    class Meta:
        indexes = (models.Index(fields=("assigned_object_type", "assigned_object_id")),)
        constraints = (
            models.UniqueConstraint(
                fields=("assigned_object_type", "assigned_object_id", "pool"),
                name="%(app_label)s_%(class)s_unique_pool",
            ),
        )
        verbose_name = _("LB Pool Assignment")
        verbose_name_plural = _("LB Pool Assignments")

    def __str__(self):
        return f"{self.assigned_object}: {self.pool}"

    def get_absolute_url(self):
        if self.assigned_object:
            return self.assigned_object.get_absolute_url()
        return None


@register_search
class PoolIndex(SearchIndex):
    model = Pool
    fields = (
        ("name", 100),
        ("description", 500),
    )


GenericRelation(
    to=PoolAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="lbservice",
).contribute_to_class(LBService, "pools")

netbox_load_balancing/models/vip_pool.py
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from netbox.models import PrimaryModel, NetBoxModel
from netbox.models.features import ContactsMixin
from netbox.search import SearchIndex, register_search
from ipam.models import IPRange, Prefix, VLAN

from netbox_load_balancing.constants import VIP_POOL_ASSIGNMENT_MODELS


class VirtualIPPool(ContactsMixin, PrimaryModel):
    name = models.CharField()
    disabled = models.BooleanField(
        default=False,
    )
    tenant = models.ForeignKey(
        to="tenancy.Tenant",
        on_delete=models.SET_NULL,
        related_name="%(class)s_related",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _("Virtual IP Pool")
        verbose_name_plural = _("Virtual IP Pools")
        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_load_balancing:virtualippool", args=[self.pk])


class VirtualIPPoolAssignment(NetBoxModel):
    assigned_object_type = models.ForeignKey(
        to="contenttypes.ContentType",
        limit_choices_to=VIP_POOL_ASSIGNMENT_MODELS,
        on_delete=models.CASCADE,
    )
    assigned_object_id = models.PositiveBigIntegerField()
    assigned_object = GenericForeignKey(
        ct_field="assigned_object_type", fk_field="assigned_object_id"
    )
    virtual_pool = models.ForeignKey(
        to="netbox_load_balancing.VirtualIPPool",
        on_delete=models.CASCADE,
        related_name="%(class)s_related",
    )
    disabled = models.BooleanField(
        default=False,
    )
    weight = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(32767),
        ],
        default=1,
    )

    clone_fields = ("assigned_object_type", "assigned_object_id")

    prerequisite_models = (
        "ipam.IPRange",
        "ipam.Prefix",
        "ipam.VLAN",
        "netbox_load_balancing.VirtualIPPool",
    )

    class Meta:
        indexes = (models.Index(fields=("assigned_object_type", "assigned_object_id")),)
        constraints = (
            models.UniqueConstraint(
                fields=("assigned_object_type", "assigned_object_id", "virtual_pool"),
                name="%(app_label)s_%(class)s_unique_virtual_pool",
            ),
        )
        verbose_name = _("Virtual Pool Assignment")
        verbose_name_plural = _("Virtual Pool Assignments")

    def __str__(self):
        return f"{self.assigned_object}: {self.virtual_pool}"

    def get_absolute_url(self):
        if self.assigned_object:
            return self.assigned_object.get_absolute_url()
        return None


@register_search
class VirtualIPPoolIndex(SearchIndex):
    model = VirtualIPPool
    fields = (
        ("name", 100),
        ("description", 500),
    )


GenericRelation(
    to=VirtualIPPoolAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="ip_range",
).contribute_to_class(IPRange, "vip_pools")

GenericRelation(
    to=VirtualIPPoolAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="prefix",
).contribute_to_class(Prefix, "vip_pools")

GenericRelation(
    to=VirtualIPPoolAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="vlan",
).contribute_to_class(VLAN, "vip_pools")

netbox_load_balancing/templates/netbox_load_balancing/assignments/member.html
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        {% trans "LB Members" %}
        <div class="card-actions">
            {% if perms.netbox_load_balancing.add_member %}
                <a href="{% url 'plugins:netbox_load_balancing:member_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create LB Member" %}
                </a>
            {% endif %}
            {% if perms.netbox_load_balancing.add_memberassignment %}
                <a href="{% url 'plugins:netbox_load_balancing:memberassignment_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign LB Member" %}
                </a>
            {% endif %}
        </div>
    </h5>
    {% render_table related_member_table 'inc/table.html' %}
</div>

netbox_load_balancing/templates/netbox_load_balancing/assignments/monitor.html
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        {% trans "LB Health Monitors" %}
        <div class="card-actions">
            {% if perms.netbox_load_balancing.add_healthmonitor %}
                <a href="{% url 'plugins:netbox_load_balancing:healthmonitor_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create LB Health Monitor" %}
                </a>
            {% endif %}
            {% if perms.netbox_load_balancing.add_healthmonitorassignment %}
                <a href="{% url 'plugins:netbox_load_balancing:healthmonitorassignment_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign LB Health Monitor" %}
                </a>
            {% endif %}          
        </div>
    </h5>
    {% render_table related_monitor_table 'inc/table.html' %}
</div>

netbox_load_balancing/templates/netbox_load_balancing/assignments/pool.html
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        {% trans "LB Pools" %}
        <div class="card-actions">
            {% if perms.netbox_load_balancing.add_pool %}
                <a href="{% url 'plugins:netbox_load_balancing:pool_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create LB Pool" %}
                </a>
            {% endif %}
            {% if perms.netbox_load_balancing.add_poolassignment %}
                <a href="{% url 'plugins:netbox_load_balancing:poolassignment_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign LB Pool" %}
                </a>
            {% endif %}          
        </div>
    </h5>
    {% render_table related_pool_table 'inc/table.html' %}
</div>

netbox_load_balancing/templates/netbox_load_balancing/assignments/service.html
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        {% trans "LB Services" %}
        <div class="card-actions">
            {% if perms.netbox_load_balancing.add_lbservice %}
                <a href="{% url 'plugins:netbox_load_balancing:lbservice_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create LB Service" %}
                </a>
            {% endif %}
            {% if perms.netbox_load_balancing.add_lbserviceassignment %}
                <a href="{% url 'plugins:netbox_load_balancing:lbserviceassignment_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign LB Service" %}
                </a>
            {% endif %}          
        </div>
    </h5>
    {% render_table related_service_table 'inc/table.html' %}
</div>

netbox_load_balancing/templates/netbox_load_balancing/assignments/virtualippool.html
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}

<div class="card">
    <h5 class="card-header">
        {% trans "Virtual Pools" %}
        <div class="card-actions">
            {% if perms.netbox_load_balancing.add_virtualippool %}
                <a href="{% url 'plugins:netbox_load_balancing:virtualippool_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Create Virtual Pool" %}
                </a>
            {% endif %}
            {% if perms.netbox_load_balancing.add_virtualippoolassignment %}
                <a href="{% url 'plugins:netbox_load_balancing:virtualippoolassignment_add' %}?assigned_object_type={{ object|content_type_id }}&assigned_object_id={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-ghost-primary btn-sm">
                  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Assign Virtual Pool" %}
                </a>
            {% endif %}          
        </div>
    </h5>
    {% render_table related_pool_table 'inc/table.html' %}
</div>