netbox_load_balancing/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls

# +
# Import views so the register_model_view is run. This is required for the
# URLs to be set up properly with get_model_urls().
# -
from .views import *  # noqa: F401

app_name = "netbox_load_balancing"

urlpatterns = [
    # Services
    path(
        "service/",
        include(get_model_urls("netbox_load_balancing", "lbservice", detail=False)),
    ),
    path(
        "service/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "lbservice")),
    ),
    # LBService Assignments
    path(
        "service-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "lbserviceassignment", detail=False)
        ),
    ),
    path(
        "service-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "lbserviceassignment")),
    ),
    # Virtual Pools
    path(
        "virtual-pool/",
        include(get_model_urls("netbox_load_balancing", "virtualippool", detail=False)),
    ),
    path(
        "virtual-pool/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualippool")),
    ),
    # Virtual Pool Assignments
    path(
        "virtual-pool-assignments/",
        include(
            get_model_urls(
                "netbox_load_balancing", "virtualippoolassignment", detail=False
            )
        ),
    ),
    path(
        "virtual-pool-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualippoolassignment")),
    ),
    # Virtual Addresses
    path(
        "virtual-address/",
        include(get_model_urls("netbox_load_balancing", "virtualip", detail=False)),
    ),
    path(
        "virtual-address/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "virtualip")),
    ),
    # Listeners
    path(
        "listener/",
        include(get_model_urls("netbox_load_balancing", "listener", detail=False)),
    ),
    path(
        "istener/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "listener")),
    ),
    # Pools
    path(
        "pool/",
        include(get_model_urls("netbox_load_balancing", "pool", detail=False)),
    ),
    path(
        "pool/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "pool")),
    ),
    # Pool Assignments
    path(
        "pool-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "poolassignment", detail=False)
        ),
    ),
    path(
        "pool-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "poolassignment")),
    ),
    # Health Monitors
    path(
        "health-monitor/",
        include(get_model_urls("netbox_load_balancing", "healthmonitor", detail=False)),
    ),
    path(
        "health-monitor/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "healthmonitor")),
    ),
    # Health Monitor Assignments
    path(
        "health-monitor-assignments/",
        include(
            get_model_urls(
                "netbox_load_balancing", "healthmonitorassignment", detail=False
            )
        ),
    ),
    path(
        "health-monitor-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "healthmonitorassignment")),
    ),
    # Members
    path(
        "member/",
        include(get_model_urls("netbox_load_balancing", "member", detail=False)),
    ),
    path(
        "member/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "member")),
    ),
    # Health Monitor Assignments
    path(
        "member-assignments/",
        include(
            get_model_urls("netbox_load_balancing", "memberassignment", detail=False)
        ),
    ),
    path(
        "member-assignments/<int:pk>/",
        include(get_model_urls("netbox_load_balancing", "memberassignment")),
    ),
]

netbox_load_balancing/models/health_monitor.py
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.postgres.fields import ArrayField
from netbox.models import PrimaryModel, NetBoxModel
from netbox.models.features import ContactsMixin
from netbox.search import SearchIndex, register_search

from netbox_load_balancing.models import Pool
from netbox_load_balancing.constants import HEALTH_MONITOR_ASSIGNMENT_MODELS
from netbox_load_balancing.choices import (
    HealthMonitorTypeChoices,
    HealthMonitorHTTPVersionChoices,
)


_all__ = ("HealthMonitor", "HealthMonitorAssignment", "HealthMonitorIndex")


class HealthMonitor(ContactsMixin, PrimaryModel):
    name = models.CharField(
        max_length=255,
    )
    template = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    type = models.CharField(
        max_length=255,
        choices=HealthMonitorTypeChoices,
        default=HealthMonitorTypeChoices.HTTP,
    )
    monitor_url = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    http_response = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    monitor_host = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    monitor_port = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(65534),
        ],
        blank=True,
        null=True,
    )
    http_version = models.CharField(
        choices=HealthMonitorHTTPVersionChoices,
        default=HealthMonitorHTTPVersionChoices.VERSION_1,
        max_length=255,
        help_text=_("HTTP Version"),
    )
    http_secure = models.BooleanField(
        default=False,
        help_text=_("Use HTTP secure connections"),
    )
    http_response_codes = ArrayField(
        base_field=models.PositiveIntegerField(
            validators=[
                MinValueValidator(100),
                MaxValueValidator(599),
            ],
            default=200,
        ),
        help_text=_(
            "List of HTTP response codes considered successful for the health check"
        ),
        blank=True,
        null=True,
    )
    probe_interval = models.PositiveIntegerField(
        help_text=_("Interval in seconds between 2 probes"),
        blank=True,
        null=True,
    )
    response_timeout = models.PositiveIntegerField(
        help_text=_(
            "Amount of time in seconds for which the monitor must wait before marking the probe as failed"
        ),
        blank=True,
        null=True,
    )
    disabled = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name = _("Health Monitor")
        verbose_name_plural = _("Health Monitors")
        ordering = ("name",)
        unique_together = ("name", "template")

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_load_balancing:healthmonitor", args=[self.pk])

    def get_type_color(self):
        return HealthMonitorTypeChoices.colors.get(self.type)

    def get_http_version_color(self):
        return HealthMonitorHTTPVersionChoices.colors.get(self.http_version)


class HealthMonitorAssignment(NetBoxModel):
    assigned_object_type = models.ForeignKey(
        to="contenttypes.ContentType",
        limit_choices_to=HEALTH_MONITOR_ASSIGNMENT_MODELS,
        on_delete=models.CASCADE,
    )
    assigned_object_id = models.PositiveBigIntegerField()
    assigned_object = GenericForeignKey(
        ct_field="assigned_object_type", fk_field="assigned_object_id"
    )
    monitor = models.ForeignKey(
        to="netbox_load_balancing.HealthMonitor", on_delete=models.CASCADE
    )
    disabled = models.BooleanField(
        default=False,
    )
    weight = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(32767),
        ],
        default=1,
    )
    clone_fields = ("assigned_object_type", "assigned_object_id")

    prerequisite_models = (
        "netbox_load_balancing.HealthMonitor",
        "netbox_load_balancing.Pool",
    )

    class Meta:
        indexes = (models.Index(fields=("assigned_object_type", "assigned_object_id")),)
        constraints = (
            models.UniqueConstraint(
                fields=("assigned_object_type", "assigned_object_id", "monitor"),
                name="%(app_label)s_%(class)s_unique_monitor",
            ),
        )
        verbose_name = _("LB Health Monitor Assignment")
        verbose_name_plural = _("LB Health Monitor Assignments")

    def __str__(self):
        return f"{self.assigned_object}: {self.monitor}"

    def get_absolute_url(self):
        if self.assigned_object:
            return self.assigned_object.get_absolute_url()
        return None


@register_search
class HealthMonitorIndex(SearchIndex):
    model = HealthMonitor
    fields = (
        ("name", 100),
        ("description", 500),
    )


GenericRelation(
    to=HealthMonitorAssignment,
    content_type_field="assigned_object_type",
    object_id_field="assigned_object_id",
    related_query_name="health_monitor",
).contribute_to_class(Pool, "health_monitors")

netbox_load_balancing/models/listener.py
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from netbox.models import PrimaryModel
from netbox.models.features import ContactsMixin
from netbox.search import SearchIndex, register_search

from netbox_load_balancing.choices import ListenerProtocolChoices


_all__ = ("Listener", "ListenerIndex")


class Listener(ContactsMixin, PrimaryModel):
    name = models.CharField(
        max_length=255,
    )
    service = models.ForeignKey(
        to="netbox_load_balancing.LBService",
        on_delete=models.CASCADE,
        related_name="%(class)s_service",
    )
    port = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(65534),
        ],
        help_text=_("Listener Port"),
    )
    protocol = models.CharField(
        max_length=255,
        choices=ListenerProtocolChoices,
        default=ListenerProtocolChoices.TCP,
        help_text=_("Pool Protocol"),
    )
    source_nat = models.BooleanField(
        default=True, help_text=_("Enable or disable SNAT")
    )
    use_proxy_port = models.BooleanField(
        default=False,
        help_text=_("Use Load Balancer source port when SNAT is disabled"),
    )
    max_clients = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(4294967295),
        ],
        default=0,
        help_text=_(
            "Maximum number of connections that can be sent on a persistent connection"
        ),
    )
    max_requests = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(4294967295),
        ],
        default=0,
        help_text=_(
            "Maximum number of requests that can be sent on a persistent connection"
        ),
    )
    client_timeout = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(31536000),
        ],
        default=9000,
        help_text=_(
            "Time in seconds after which to terminate an idle client connection"
        ),
    )
    server_timeout = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(31536000),
        ],
        default=9000,
        help_text=_(
            "Time in seconds after which to terminate an idle server connection"
        ),
    )
    client_keepalive = models.BooleanField(
        default=False,
        help_text=_(
            "The Client KeepAlive mode enables the Load Balancer to process multiple requests using the same socket connection"
        ),
    )
    surge_protection = models.BooleanField(
        default=False,
        help_text="When enabled, surge protection ensures that connections to the server occur at a rate the server can handle",
    )
    tcp_buffering = models.BooleanField(
        default=False,
        help_text="TCP buffering option only buffers responses from the load balanced server",
    )
    compression = models.BooleanField(
        default=False,
        help_text="Compression option allows to transparently compress HTML/TEXT files by using a set of built-in compression policies",
    )
    prerequisite_models = ("netbox_load_balancing.LBService",)

    class Meta:
        verbose_name = _("Listener")
        verbose_name_plural = _("Listeners")
        ordering = ("name", "port")
        unique_together = ("name", "service")

    def __str__(self):
        return f"{self.name}: {self.port}"

    def get_absolute_url(self):
        return reverse("plugins:netbox_load_balancing:listener", args=[self.pk])

    def get_protocol_color(self):
        return ListenerProtocolChoices.colors.get(self.protocol)


@register_search
class ListenerIndex(SearchIndex):
    model = Listener
    fields = (
        ("name", 100),
        ("description", 500),
    )

netbox_load_balancing/views/health_monitor.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404

from netbox.views import generic
from utilities.views import register_model_view

from netbox_load_balancing.tables import HealthMonitorTable
from netbox_load_balancing.filtersets import HealthMonitorFilterSet

from netbox_load_balancing.models import HealthMonitor, HealthMonitorAssignment
from netbox_load_balancing.forms import (
    HealthMonitorFilterForm,
    HealthMonitorForm,
    HealthMonitorBulkEditForm,
    HealthMonitorAssignmentForm,
    HealthMonitorImportForm,
)


__all__ = (
    "HealthMonitorView",
    "HealthMonitorListView",
    "HealthMonitorEditView",
    "HealthMonitorDeleteView",
    "HealthMonitorBulkEditView",
    "HealthMonitorBulkDeleteView",
    "HealthMonitorBulkImportView",
    "HealthMonitorAssignmentEditView",
    "HealthMonitorAssignmentDeleteView",
)


@register_model_view(HealthMonitor)
class HealthMonitorView(generic.ObjectView):
    queryset = HealthMonitor.objects.all()
    template_name = "netbox_load_balancing/healthmonitor.html"


@register_model_view(HealthMonitor, "list", path="", detail=False)
class HealthMonitorListView(generic.ObjectListView):
    queryset = HealthMonitor.objects.all()
    filterset = HealthMonitorFilterSet
    filterset_form = HealthMonitorFilterForm
    table = HealthMonitorTable


@register_model_view(HealthMonitor, "add", detail=False)
@register_model_view(HealthMonitor, "edit")
class HealthMonitorEditView(generic.ObjectEditView):
    queryset = HealthMonitor.objects.all()
    form = HealthMonitorForm


@register_model_view(HealthMonitor, "delete")
class HealthMonitorDeleteView(generic.ObjectDeleteView):
    queryset = HealthMonitor.objects.all()


@register_model_view(HealthMonitor, "bulk_edit", path="edit", detail=False)
class HealthMonitorBulkEditView(generic.BulkEditView):
    queryset = HealthMonitor.objects.all()
    filterset = HealthMonitorFilterSet
    table = HealthMonitorTable
    form = HealthMonitorBulkEditForm


@register_model_view(HealthMonitor, "bulk_delete", path="delete", detail=False)
class HealthMonitorBulkDeleteView(generic.BulkDeleteView):
    queryset = HealthMonitor.objects.all()
    table = HealthMonitorTable


@register_model_view(HealthMonitor, "bulk_import", detail=False)
class HealthMonitorBulkImportView(generic.BulkImportView):
    queryset = HealthMonitor.objects.all()
    model_form = HealthMonitorImportForm


@register_model_view(HealthMonitorAssignment, "add", detail=False)
@register_model_view(HealthMonitorAssignment, "edit")
class HealthMonitorAssignmentEditView(generic.ObjectEditView):
    queryset = HealthMonitorAssignment.objects.all()
    form = HealthMonitorAssignmentForm

    def alter_object(self, instance, request, args, kwargs):
        if not instance.pk:
            content_type = get_object_or_404(
                ContentType, pk=request.GET.get("assigned_object_type")
            )
            instance.assigned_object = get_object_or_404(
                content_type.model_class(), pk=request.GET.get("assigned_object_id")
            )
        return instance

    def get_extra_addanother_params(self, request):
        return {
            "assigned_object_type": request.GET.get("assigned_object_type"),
            "assigned_object_id": request.GET.get("assigned_object_id"),
        }


@register_model_view(HealthMonitorAssignment, "delete")
class HealthMonitorAssignmentDeleteView(generic.ObjectDeleteView):
    queryset = HealthMonitorAssignment.objects.all()

netbox_load_balancing/templates/netbox_load_balancing/healthmonitor.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Health Monitors" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Type" %}</th>
                    <td>{% badge object.get_type_display bg_color=object.get_type_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "HTTP Version" %}</th>
                    <td>{% badge object.get_http_version_display bg_color=object.get_http_version_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Monitor URL" %}</th>
                    <td>{{ object.monitor_url }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "HTTP Response" %}</th>
                    <td>{{ object.http_response }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Monitor Host" %}</th>
                    <td>{{ object.monitor_host }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Monitor Port" %}</th>
                    <td>{{ object.monitor_port }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "HTTP Secure" %}</th>
                    <td>{% checkmark object.http_secure %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "HTTP Response Codes" %}</th>
                    <td>{{ object.http_response_codes }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Probe Interval" %}</th>
                    <td>{{ object.probe_interval }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Response Timeout" %}</th>
                    <td>{{ object.response_timeout }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Disabled" %}</th>
                    <td>{% checkmark object.disabled %}</td>
                </tr>
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% plugin_right_page object %}
    </div>
    {% plugin_full_width_page object %}
</div>
{% endblock %}

netbox_load_balancing/templates/netbox_load_balancing/lbservice.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Services" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Reference" %}</th>
                    <td>{{ object.reference }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Disabled" %}</th>
                    <td>{% checkmark object.disabled %}</td>
                </tr>
                {% if object.tenant %}
                <tr>
                    <th scope="row">{% trans "Tenant" %}</th>
                    <td>
                        {% if object.tenant.group %}
                            {{ object.tenant.group|linkify }} /
                        {% endif %}
                        {{ object.tenant|linkify|placeholder }}
                    </td>
                </tr>
                {% endif %}
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% plugin_right_page object %}
    </div>
    {% plugin_full_width_page object %}
</div>
{% endblock %}

netbox_load_balancing/templates/netbox_load_balancing/listener.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Listeners" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Service" %}</th>
                    <td>{{ object.service|linkify|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Port" %}</th>
                    <td>{{ object.port }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Protocol" %}</th>
                    <td>{% badge object.get_protocol_display bg_color=object.get_protocol_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Source NAT" %}</th>
                    <td>{% checkmark object.source_nat %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Use Proxy Port" %}</th>
                    <td>{% checkmark object.use_proxy_port %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "MAX Clients" %}</th>
                    <td>{{ object.max_clients }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "MAX Requests" %}</th>
                    <td>{{ object.max_requests }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Client Timeout" %}</th>
                    <td>{{ object.client_timeout }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Server Timeout" %}</th>
                    <td>{{ object.server_timeout }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Client Keepalive" %}</th>
                    <td>{% checkmark object.client_keepalive %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Surge Protection" %}</th>
                    <td>{% checkmark object.surge_protection %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "TCP Buffering" %}</th>
                    <td>{% checkmark object.tcp_buffering %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Compression" %}</th>
                    <td>{% checkmark object.compression %}</td>
                </tr>
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
    </div>
</div>
{% endblock %}

netbox_load_balancing/templates/netbox_load_balancing/member.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Members" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Reference" %}</th>
                    <td>{{ object.reference|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "IP Address" %}</th>
                    <td>{{ object.ip_address|linkify|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Disabled" %}</th>
                    <td>{% checkmark object.disabled %}</td>
                </tr>
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
    </div>
</div>
{% endblock %}

netbox_load_balancing/templates/netbox_load_balancing/pool.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Pools" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Algorythm" %}</th>
                    <td>{% badge object.get_algorythm_display bg_color=object.get_algorythm_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Session Persistence" %}</th>
                    <td>{% badge object.get_session_persistence_display bg_color=object.get_session_persistence_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Backup Persistence" %}</th>
                    <td>{% badge object.get_backup_persistence_display bg_color=object.get_backup_persistence_color %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Persistence Timeout" %}</th>
                    <td>{{ object.persistence_timeout|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Backup Timeout" %}</th>
                    <td>{{ object.backup_timeout|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Member Port" %}</th>
                    <td>{{ object.member_port|placeholder }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Disabled" %}</th>
                    <td>{% checkmark object.disabled %}</td>
                </tr>
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% plugin_right_page object %}
    </div>
    {% plugin_full_width_page object %}
</div>
{% endblock %}

netbox_load_balancing/templates/netbox_load_balancing/virtualip.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load plugins %}
{% load humanize %}
{% load helpers %}

{% block content %}
<div class="row">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">{% trans "Virtual IP" %}</h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "DNS Name" %}</th>
                    <td>{{ object.dns_name }}</td>
                </tr>
                {% if object.description %}
                <tr>
                    <th scope="row">{% trans "Description" %}</th>
                    <td>{{ object.description|placeholder }}</td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">{% trans "Disabled" %}</th>
                    <td>{% checkmark object.disabled %}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Route Health Injection" %}</th>
                    <td>{% checkmark object.route_health_injection %}</td>
                </tr>
                {% if object.virtual_pool %}
                <tr>
                    <th scope="row">{% trans "Virtual Pool" %}</th>
                    <td>
                        {{ object.virtual_pool|linkify|placeholder }}
                    </td>
                </tr>
                {% endif %}
                {% if object.address %}
                <tr>
                    <th scope="row">{% trans "IP Address" %}</th>
                    <td>
                        {{ object.address|linkify|placeholder }}
                    </td>
                </tr>
                {% endif %}
            </table>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
        {% plugin_left_page object %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
        {% plugin_right_page object %}
    </div>
    {% plugin_full_width_page object %}
</div>
{% endblock %}